apiVersion: v1
kind: PersistentVolume
metadata:
  name: winesaps-mysql-pv-volume
  labels:
    type: local
    app: mysql-label
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/mysqldata"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: winesaps-mysql-pv-claim
  labels:
    app: mysql-label
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
